type: object
properties:
  success:
    type: boolean
    example: true
  message:
    type: string
    nullable: true
  result:
    type: object
    properties:
      product_id:
        type: integer
        example: 65
      title:
        type: string
        example: "aa"
      description:
        type: string
        example: "aaa"
      product_attributes:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
              example: 99
            name:
              type: string
              example: "Thương hiệu"
            value:
              type: string
              example: "No Brand"
      cate_levels:
        type: object
        properties:
          "1":
            type: object
            properties:
              cate_id:
                type: integer
              name:
                type: string
              level:
                type: integer
              parent_id:
                type: integer
                nullable: true
              image_url:
                type: string
          "2":
            type: object
            properties:
              cate_id:
                type: integer
              name:
                type: string
              level:
                type: integer
              parent_id:
                type: integer
                nullable: true
              image_url:
                type: string
      options:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            value:
              type: array
              items:
                type: string
      variants:
        type: array
        items:
          type: object
          properties:
            variant_id:
              type: integer
            sku:
              type: string
            name:
              type: string
            price:
              type: integer
            price_before_discount:
              type: integer
            sold:
              type: integer
            stock:
              type: integer
      product_price:
        type: object
        properties:
          price:
            type: integer
          price_before_discount:
            type: integer
          discount:
            type: number
          range_min:
            type: integer
          range_max:
            type: integer
          range_min_before_discount:
            type: integer
          range_max_before_discount:
            type: integer
      shipping_channel:
        type: array
        items:
          type: object
          properties:
            channel_id:
              type: integer
            name:
              type: string
            fee:
              type: integer
            freeship:
              type: boolean
            estimated_delivery_days_min:
              type: integer
            estimated_delivery_days_max:
              type: integer
            estimated_delivery_date_from:
              type: integer
            estimated_delivery_date_to:
              type: integer
            delivery_text:
              type: string
      image_urls:
        type: array
        items:
          type: string
      shop:
        type: object
        properties:
          shopid:
            type: integer
          account:
            type: object
            properties:
              user_id:
                type: string
              username:
                type: string
              email:
                type: string
              name:
                type: string
                nullable: true
              gender:
                type: integer
              phone:
                type: string
                nullable: true
              is_shop:
                type: boolean
              status:
                type: integer
              avatar:
                type: string
                nullable: true
          description:
            type: string
            nullable: true
          name:
            type: string
          item_count:
            type: integer
          rating_star:
            type: integer
          total_rating:
            type: integer
          response_rate:
            type: integer
          response_time:
            type: integer
          follower_count:
            type: integer
          created_at:
            type: integer
          default_address:
            type: integer
      sku:
        type: string
        example: "KSHSO"