import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateAll1740714982216 implements MigrationInterface {
    name = 'UpdateAll1740714982216'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`images\` DROP FOREIGN KEY IF EXISTS \`FK_96fabbb1202770b8e6a58bf6f1d\``);
        await queryRunner.query(`ALTER TABLE \`options\` DROP FOREIGN KEY IF EXISTS \`FK_8f509b13eba74e88f50da0d1133\``);
        await queryRunner.query(`ALTER TABLE \`option_values\` DROP FOREIGN KEY IF EXISTS \`FK_866eecd9bde39fd5bc4b8d86369\``);
        await queryRunner.query(`ALTER TABLE \`product_variants\` DROP FOREIGN KEY IF EXISTS \`FK_6343513e20e2deab45edfce1316\``);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` DROP FOREIGN KEY IF EXISTS \`FK_84d26b8d3aca1b113b0a423b83c\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY IF EXISTS \`FK_9e952e93f369f16e27dd786c33f\``);
        await queryRunner.query(`ALTER TABLE \`carts\` DROP FOREIGN KEY IF EXISTS \`FK_2ec1c94a977b940d85a4f498aea\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP FOREIGN KEY IF EXISTS \`FK_30e89257a105eab7648a35c7fce\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP FOREIGN KEY IF EXISTS \`FK_ad4336ea52ca96a9094a76cd9f3\``);
        await queryRunner.query(`ALTER TABLE \`shops\` DROP FOREIGN KEY IF EXISTS \`FK_bb9c758dcc60137e56f6fee72f7\``);
        await queryRunner.query(`ALTER TABLE \`addresses\` DROP FOREIGN KEY IF EXISTS \`FK_3e27a8fc336ce24a08833ae34f2\``);
        await queryRunner.query(`ALTER TABLE \`addresses\` DROP FOREIGN KEY IF EXISTS \`FK_9d48998b97e7a97c4fddab1463b\``);
        // await queryRunner.query(`ALTER TABLE \`attribute_values\` DROP FOREIGN KEY IF EXISTS \`REL_be02d0f6a15bc7a0d835f832b6\``);
        // await queryRunner.query(`DROP INDEX IF EXISTS \`REL_be02d0f6a15bc7a0d835f832b6\` ON \`attribute_values\``);
        await queryRunner.query(`DROP TABLE IF EXISTS \`shipping_product_infos\``);
        await queryRunner.query(`DROP TABLE IF EXISTS \`product_options\``);

        await queryRunner.query(`CREATE TABLE \`shipping_product_infos\` (\`id\` int NOT NULL AUTO_INCREMENT, \`fee\` int NOT NULL, \`estimated_delivery_days_min\` int NOT NULL, \`estimated_delivery_days_max\` int NOT NULL, \`freeship\` tinyint NOT NULL DEFAULT 0, \`product_id\` int NULL, \`shipping_channel_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product_options\` (\`product_id\` int NOT NULL, \`option_id\` int NOT NULL, INDEX \`IDX_49677f87ad61a8b2a31f33c8a2\` (\`product_id\`), INDEX \`IDX_8d17fb61344ff9acf7b706ae02\` (\`option_id\`), PRIMARY KEY (\`product_id\`, \`option_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`options\` DROP COLUMN IF EXISTS \`product_id\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN IF EXISTS \`range_min_price\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN IF EXISTS \`range_max_price\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN IF EXISTS \`price_range_min\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN IF EXISTS \`price_range_max\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN IF EXISTS \`price_range_min_old\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN IF EXISTS \`price_range_max_old\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN IF EXISTS \`discount\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN IF EXISTS \`weight\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN IF EXISTS \`width\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN IF EXISTS \`height\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN IF EXISTS \`length\``);
        
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`price_range_min\` int NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`price_range_max\` int NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`price_range_min_old\` int NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`price_range_max_old\` int NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`discount\` float NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`weight\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`width\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`height\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`length\` int NULL`);
        
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP COLUMN IF EXISTS \`cart_id\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD \`cart_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`shops\` DROP COLUMN IF EXISTS \`shop_location\``);
        await queryRunner.query(`ALTER TABLE \`shops\` ADD \`shop_location\` varchar(255) NULL`);
        
        // await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`parent_cate_id\` \`parent_cate_id\` int NULL`);
        // await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`image_url\` \`image_url\` varchar(255) NULL`);
        // await queryRunner.query(`ALTER TABLE \`brands\` CHANGE \`image_url\` \`image_url\` varchar(255) NULL`);
        // await queryRunner.query(`ALTER TABLE \`images\` CHANGE \`product_id\` \`product_id\` int NULL`);
        // await queryRunner.query(`ALTER TABLE \`shippings\` CHANGE \`desc\` \`desc\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`shipping_details\` DROP FOREIGN KEY IF EXISTS \`FK_565cbf97ee9de5d1f046e01ea8b\``);
        await queryRunner.query(`ALTER TABLE \`shipping_details\` DROP FOREIGN KEY IF EXISTS \`FK_a9fe3ec588dbd5110ab7550406e\``);
        await queryRunner.query(`ALTER TABLE \`shipping_details\` DROP FOREIGN KEY IF EXISTS \`FK_bf120744766b0d4fd8e6a35005b\``);
        // await queryRunner.query(`ALTER TABLE \`shipping_details\` CHANGE \`shipping_channel_id\` \`shipping_channel_id\` int NULL`);
        // await queryRunner.query(`ALTER TABLE \`shipping_details\` CHANGE \`order_id\` \`order_id\` varchar(36) NULL`);
        // await queryRunner.query(`ALTER TABLE \`shipping_details\` CHANGE \`address_id\` \`address_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY IF EXISTS \`FK_a922b820eeef29ac1c6800e826a\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY IF EXISTS \`FK_899f633317d513749082e4aadff\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY IF EXISTS \`FK_33f20db82908f7685a5c0c58ac6\``);
        // await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`desc\` \`desc\` text NULL`);
        // await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`user_id\` \`user_id\` varchar(36) NULL`);
        // await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`shipping_detail_id\` \`shipping_detail_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`shop_id\` \`shop_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY IF EXISTS \`FK_145532db85752b29c57d2b7b1f1\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY IF EXISTS \`FK_9263386c35b6b242540f9493b00\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY IF EXISTS \`FK_11836543386b9135a47d54cab70\``);
        // await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`order_id\` \`order_id\` varchar(36) NULL`);
        // await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`product_id\` \`product_id\` int NULL`);
        // await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`product_variant_id\` \`product_variant_id\` int NULL`);
        // await queryRunner.query(`ALTER TABLE \`option_values\` CHANGE \`image_url\` \`image_url\` varchar(255) NULL`);
        // await queryRunner.query(`ALTER TABLE \`option_values\` CHANGE \`option_id\` \`option_id\` int NULL`);
        // await queryRunner.query(`ALTER TABLE \`product_variants\` CHANGE \`old_price\` \`old_price\` int NULL`);
        // await queryRunner.query(`ALTER TABLE \`product_variants\` CHANGE \`image_url\` \`image_url\` varchar(255) NULL`);
        // await queryRunner.query(`ALTER TABLE \`product_variants\` CHANGE \`product_id\` \`product_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` DROP FOREIGN KEY IF EXISTS \`FK_be02d0f6a15bc7a0d835f832b62\``);
        // await queryRunner.query(`ALTER TABLE \`attribute_values\` DROP PRIMARY KEY KEY IF EXISTS`);
        // await queryRunner.query(`ALTER TABLE \`attribute_values\` ADD PRIMARY KEY (\`product_id\`)`);
        // await queryRunner.query(`ALTER TABLE \`attribute_values\` DROP IF EXISTS \`id\``);
        // await queryRunner.query(`ALTER TABLE \`attribute_values\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` ADD PRIMARY KEY (\`product_id\`, \`id\`)`);
        // await queryRunner.query(`ALTER TABLE \`attribute_values\` CHANGE \`attribute_id\` \`attribute_id\` int NULL`);
        // await queryRunner.query(`ALTER TABLE \`attribute_values\` CHANGE \`product_id\` \`product_id\` int NULL`);
        // await queryRunner.query(`ALTER TABLE \`attribute_values\` CHANGE \`id\` \`id\` int NOT NULL`);
        // await queryRunner.query(`ALTER TABLE \`attribute_values\` DROP PRIMARY KEY`);
        // await queryRunner.query(`ALTER TABLE \`attribute_values\` ADD PRIMARY KEY (\`id\`)`);
        // await queryRunner.query(`ALTER TABLE \`attribute_values\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY IF EXISTS \`FK_1530a6f15d3c79d1b70be98f2be\``);
        // await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`description\` \`description\` text NULL`);
        // await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`specification\` \`specification\` text NULL`);
        // await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`brand_id\` \`brand_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`shop_id\` \`shop_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`carts\` DROP COLUMN IF EXISTS \`total\``);
        await queryRunner.query(`ALTER TABLE \`carts\` ADD \`total\` int NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`carts\` DROP COLUMN IF EXISTS \`total_before_discount\``);
        await queryRunner.query(`ALTER TABLE \`carts\` ADD \`total_before_discount\` int NULL DEFAULT '0'`);
        // await queryRunner.query(`ALTER TABLE \`carts\` CHANGE \`user_id\` \`user_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP FOREIGN KEY IF EXISTS \`FK_de29bab7b2bb3b49c07253275f1\``);
        // await queryRunner.query(`ALTER TABLE \`cart_items\` CHANGE \`product_id\` \`product_id\` int NULL`);
        // await queryRunner.query(`ALTER TABLE \`cart_items\` CHANGE \`product_variant_id\` \`product_variant_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` CHANGE \`shop_id\` \`shop_id\` int NULL`);
        // await queryRunner.query(`ALTER TABLE \`shops\` CHANGE \`description\` \`description\` text NULL`);
        // await queryRunner.query(`ALTER TABLE \`shops\` CHANGE \`avatar\` \`avatar\` text NULL`);
        // await queryRunner.query(`ALTER TABLE \`shops\` CHANGE \`last_time_active\` \`last_time_active\` datetime NULL`);
        // await queryRunner.query(`ALTER TABLE \`shops\` CHANGE \`default_address_id\` \`default_address_id\` int NULL`);
        // await queryRunner.query(`ALTER TABLE \`shops\` ADD UNIQUE INDEX \`IDX_bf25720b50f0a6da3235c292d9\` (\`default_address_id\`)`);
        // await queryRunner.query(`ALTER TABLE \`shops\` CHANGE \`user_id\` \`user_id\` varchar(36) NULL`);
        // await queryRunner.query(`ALTER TABLE \`addresses\` CHANGE \`user\` \`user\` varchar(36) NULL`);
        // await queryRunner.query(`ALTER TABLE \`addresses\` CHANGE \`shop\` \`shop\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY IF EXISTS \`FK_cbfb19ddc0218b26522f9fea2eb\``);
        // await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`name\` \`name\` varchar(255) NULL`);
        // await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`dob\` \`dob\` datetime NULL`);
        // await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phone\` \`phone\` varchar(255) NULL`);
        // await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`refresh_token\` \`refresh_token\` text NULL`);
        // await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`refresh_token_mobile\` \`refresh_token_mobile\` text NULL`);
        // await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`avatar\` \`avatar\` text NULL`);
        // await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`default_address_id\` \`default_address_id\` int NULL`);
        // await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`cart_id\` \`cart_id\` int NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_bf25720b50f0a6da3235c292d9\` ON \`shops\` (\`default_address_id\`)`);
        await queryRunner.query(`ALTER TABLE \`images\` ADD CONSTRAINT \`FK_96fabbb1202770b8e6a58bf6f1d\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shipping_product_infos\` ADD CONSTRAINT \`FK_c2d6ad0410696a652e80eae18e1\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shipping_product_infos\` ADD CONSTRAINT \`FK_bfa92764262768ce8f1559043cb\` FOREIGN KEY (\`shipping_channel_id\`) REFERENCES \`shippings\`(\`shipping_channel_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shipping_details\` ADD CONSTRAINT \`FK_565cbf97ee9de5d1f046e01ea8b\` FOREIGN KEY (\`shipping_channel_id\`) REFERENCES \`shippings\`(\`shipping_channel_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shipping_details\` ADD CONSTRAINT \`FK_a9fe3ec588dbd5110ab7550406e\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`shipping_channel_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shipping_details\` ADD CONSTRAINT \`FK_bf120744766b0d4fd8e6a35005b\` FOREIGN KEY (\`address_id\`) REFERENCES \`addresses\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_a922b820eeef29ac1c6800e826a\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_899f633317d513749082e4aadff\` FOREIGN KEY (\`shipping_detail_id\`) REFERENCES \`shipping_details\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_33f20db82908f7685a5c0c58ac6\` FOREIGN KEY (\`shop_id\`) REFERENCES \`shops\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_145532db85752b29c57d2b7b1f1\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`shipping_channel_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_9263386c35b6b242540f9493b00\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_11836543386b9135a47d54cab70\` FOREIGN KEY (\`product_variant_id\`) REFERENCES \`product_variants\`(\`variant_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`option_values\` ADD CONSTRAINT \`FK_866eecd9bde39fd5bc4b8d86369\` FOREIGN KEY (\`option_id\`) REFERENCES \`options\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` ADD CONSTRAINT \`FK_6343513e20e2deab45edfce1316\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` ADD CONSTRAINT \`FK_be02d0f6a15bc7a0d835f832b62\` FOREIGN KEY (\`attribute_id\`) REFERENCES \`attributes\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` ADD CONSTRAINT \`FK_84d26b8d3aca1b113b0a423b83c\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_1530a6f15d3c79d1b70be98f2be\` FOREIGN KEY (\`brand_id\`) REFERENCES \`brands\`(\`_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_9e952e93f369f16e27dd786c33f\` FOREIGN KEY (\`shop_id\`) REFERENCES \`shops\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carts\` ADD CONSTRAINT \`FK_2ec1c94a977b940d85a4f498aea\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD CONSTRAINT \`FK_6385a745d9e12a89b859bb25623\` FOREIGN KEY (\`cart_id\`) REFERENCES \`carts\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD CONSTRAINT \`FK_30e89257a105eab7648a35c7fce\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`_id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD CONSTRAINT \`FK_de29bab7b2bb3b49c07253275f1\` FOREIGN KEY (\`product_variant_id\`) REFERENCES \`product_variants\`(\`variant_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD CONSTRAINT \`FK_ad4336ea52ca96a9094a76cd9f3\` FOREIGN KEY (\`shop_id\`) REFERENCES \`shops\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shops\` ADD CONSTRAINT \`FK_bb9c758dcc60137e56f6fee72f7\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shops\` ADD CONSTRAINT \`FK_bf25720b50f0a6da3235c292d9a\` FOREIGN KEY (\`default_address_id\`) REFERENCES \`addresses\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`addresses\` ADD CONSTRAINT \`FK_3e27a8fc336ce24a08833ae34f2\` FOREIGN KEY (\`user\`) REFERENCES \`users\`(\`_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`addresses\` ADD CONSTRAINT \`FK_9d48998b97e7a97c4fddab1463b\` FOREIGN KEY (\`shop\`) REFERENCES \`shops\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_cbfb19ddc0218b26522f9fea2eb\` FOREIGN KEY (\`cart_id\`) REFERENCES \`carts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_options\` ADD CONSTRAINT \`FK_49677f87ad61a8b2a31f33c8a2c\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`_id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`product_options\` ADD CONSTRAINT \`FK_8d17fb61344ff9acf7b706ae022\` FOREIGN KEY (\`option_id\`) REFERENCES \`options\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`product_options\` DROP FOREIGN KEY IF EXISTS \`FK_8d17fb61344ff9acf7b706ae022\``);
        await queryRunner.query(`ALTER TABLE \`product_options\` DROP FOREIGN KEY IF EXISTS \`FK_49677f87ad61a8b2a31f33c8a2c\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY IF EXISTS \`FK_cbfb19ddc0218b26522f9fea2eb\``);
        await queryRunner.query(`ALTER TABLE \`addresses\` DROP FOREIGN KEY IF EXISTS \`FK_9d48998b97e7a97c4fddab1463b\``);
        await queryRunner.query(`ALTER TABLE \`addresses\` DROP FOREIGN KEY IF EXISTS \`FK_3e27a8fc336ce24a08833ae34f2\``);
        await queryRunner.query(`ALTER TABLE \`shops\` DROP FOREIGN KEY IF EXISTS \`FK_bf25720b50f0a6da3235c292d9a\``);
        await queryRunner.query(`ALTER TABLE \`shops\` DROP FOREIGN KEY IF EXISTS \`FK_bb9c758dcc60137e56f6fee72f7\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP FOREIGN KEY IF EXISTS \`FK_ad4336ea52ca96a9094a76cd9f3\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP FOREIGN KEY IF EXISTS \`FK_de29bab7b2bb3b49c07253275f1\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP FOREIGN KEY IF EXISTS \`FK_30e89257a105eab7648a35c7fce\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP FOREIGN KEY IF EXISTS \`FK_6385a745d9e12a89b859bb25623\``);
        await queryRunner.query(`ALTER TABLE \`carts\` DROP FOREIGN KEY IF EXISTS \`FK_2ec1c94a977b940d85a4f498aea\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY IF EXISTS \`FK_9e952e93f369f16e27dd786c33f\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY IF EXISTS \`FK_1530a6f15d3c79d1b70be98f2be\``);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` DROP FOREIGN KEY IF EXISTS \`FK_84d26b8d3aca1b113b0a423b83c\``);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` DROP FOREIGN KEY IF EXISTS \`FK_be02d0f6a15bc7a0d835f832b62\``);
        await queryRunner.query(`ALTER TABLE \`product_variants\` DROP FOREIGN KEY IF EXISTS \`FK_6343513e20e2deab45edfce1316\``);
        await queryRunner.query(`ALTER TABLE \`option_values\` DROP FOREIGN KEY IF EXISTS \`FK_866eecd9bde39fd5bc4b8d86369\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY IF EXISTS \`FK_11836543386b9135a47d54cab70\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY IF EXISTS \`FK_9263386c35b6b242540f9493b00\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY IF EXISTS \`FK_145532db85752b29c57d2b7b1f1\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY IF EXISTS \`FK_33f20db82908f7685a5c0c58ac6\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY IF EXISTS \`FK_899f633317d513749082e4aadff\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY IF EXISTS \`FK_a922b820eeef29ac1c6800e826a\``);
        await queryRunner.query(`ALTER TABLE \`shipping_details\` DROP FOREIGN KEY IF EXISTS \`FK_bf120744766b0d4fd8e6a35005b\``);
        await queryRunner.query(`ALTER TABLE \`shipping_details\` DROP FOREIGN KEY IF EXISTS \`FK_a9fe3ec588dbd5110ab7550406e\``);
        await queryRunner.query(`ALTER TABLE \`shipping_details\` DROP FOREIGN KEY IF EXISTS \`FK_565cbf97ee9de5d1f046e01ea8b\``);
        await queryRunner.query(`ALTER TABLE \`shipping_product_infos\` DROP FOREIGN KEY IF EXISTS \`FK_bfa92764262768ce8f1559043cb\``);
        await queryRunner.query(`ALTER TABLE \`shipping_product_infos\` DROP FOREIGN KEY IF EXISTS \`FK_c2d6ad0410696a652e80eae18e1\``);
        await queryRunner.query(`ALTER TABLE \`images\` DROP FOREIGN KEY IF EXISTS \`FK_96fabbb1202770b8e6a58bf6f1d\``);
        await queryRunner.query(`DROP INDEX \`REL_bf25720b50f0a6da3235c292d9\` ON \`shops\``);
        // await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`cart_id\` \`cart_id\` int NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`default_address_id\` \`default_address_id\` int NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`avatar\` \`avatar\` text NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`refresh_token_mobile\` \`refresh_token_mobile\` text NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`refresh_token\` \`refresh_token\` text NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phone\` \`phone\` varchar(255) NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`dob\` \`dob\` datetime NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`name\` \`name\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_cbfb19ddc0218b26522f9fea2eb\` FOREIGN KEY (\`cart_id\`) REFERENCES \`carts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`addresses\` CHANGE \`shop\` \`shop\` int NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`addresses\` CHANGE \`user\` \`user\` varchar(36) NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`shops\` CHANGE \`user_id\` \`user_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`shops\` DROP INDEX \`IDX_bf25720b50f0a6da3235c292d9\``);
        // await queryRunner.query(`ALTER TABLE \`shops\` CHANGE \`default_address_id\` \`default_address_id\` int NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`shops\` CHANGE \`last_time_active\` \`last_time_active\` datetime NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`shops\` CHANGE \`avatar\` \`avatar\` text NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`shops\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` CHANGE \`shop_id\` \`shop_id\` int NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`cart_items\` CHANGE \`product_variant_id\` \`product_variant_id\` int NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`cart_items\` CHANGE \`product_id\` \`product_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD CONSTRAINT \`FK_de29bab7b2bb3b49c07253275f1\` FOREIGN KEY (\`product_variant_id\`) REFERENCES \`product_variants\`(\`variant_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        // await queryRunner.query(`ALTER TABLE \`carts\` CHANGE \`user_id\` \`user_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`carts\` DROP COLUMN IF EXISTS \`total_before_discount\``);
        await queryRunner.query(`ALTER TABLE \`carts\` ADD \`total_before_discount\` varchar(255) NULL DEFAULT ''0''`);
        await queryRunner.query(`ALTER TABLE \`carts\` DROP COLUMN IF EXISTS \`total\``);
        await queryRunner.query(`ALTER TABLE \`carts\` ADD \`total\` varchar(255) NULL DEFAULT ''0''`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`shop_id\` \`shop_id\` int NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`brand_id\` \`brand_id\` int NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`specification\` \`specification\` text NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_1530a6f15d3c79d1b70be98f2be\` FOREIGN KEY (\`brand_id\`) REFERENCES \`brands\`(\`_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        // await queryRunner.query(`ALTER TABLE \`attribute_values\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` ADD PRIMARY KEY (\`product_id\`, \`id\`)`);
        // await queryRunner.query(`ALTER TABLE \`attribute_values\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        // await queryRunner.query(`ALTER TABLE \`attribute_values\` CHANGE \`product_id\` \`product_id\` int NOT NULL`);
        // await queryRunner.query(`ALTER TABLE \`attribute_values\` CHANGE \`attribute_id\` \`attribute_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` ADD PRIMARY KEY (\`product_id\`)`);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` DROP COLUMN IF EXISTS \`id\``);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` ADD \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` ADD PRIMARY KEY (\`id\`, \`product_id\`)`);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` ADD CONSTRAINT \`FK_be02d0f6a15bc7a0d835f832b62\` FOREIGN KEY (\`attribute_id\`) REFERENCES \`attributes\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        // await queryRunner.query(`ALTER TABLE \`product_variants\` CHANGE \`product_id\` \`product_id\` int NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`product_variants\` CHANGE \`image_url\` \`image_url\` varchar(255) NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`product_variants\` CHANGE \`old_price\` \`old_price\` int NOT NULL`);
        // await queryRunner.query(`ALTER TABLE \`option_values\` CHANGE \`option_id\` \`option_id\` int NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`option_values\` CHANGE \`image_url\` \`image_url\` varchar(255) NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`product_variant_id\` \`product_variant_id\` int NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`product_id\` \`product_id\` int NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`order_id\` \`order_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_11836543386b9135a47d54cab70\` FOREIGN KEY (\`product_variant_id\`) REFERENCES \`product_variants\`(\`variant_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_9263386c35b6b242540f9493b00\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_145532db85752b29c57d2b7b1f1\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`shipping_channel_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`shop_id\` \`shop_id\` int NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`shipping_detail_id\` \`shipping_detail_id\` int NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`user_id\` \`user_id\` varchar(36) NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`desc\` \`desc\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_33f20db82908f7685a5c0c58ac6\` FOREIGN KEY (\`shop_id\`) REFERENCES \`shops\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_899f633317d513749082e4aadff\` FOREIGN KEY (\`shipping_detail_id\`) REFERENCES \`shipping_details\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_a922b820eeef29ac1c6800e826a\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        // await queryRunner.query(`ALTER TABLE \`shipping_details\` CHANGE \`address_id\` \`address_id\` int NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`shipping_details\` CHANGE \`order_id\` \`order_id\` varchar(36) NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`shipping_details\` CHANGE \`shipping_channel_id\` \`shipping_channel_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`shipping_details\` ADD CONSTRAINT \`FK_bf120744766b0d4fd8e6a35005b\` FOREIGN KEY (\`address_id\`) REFERENCES \`addresses\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shipping_details\` ADD CONSTRAINT \`FK_a9fe3ec588dbd5110ab7550406e\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`shipping_channel_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shipping_details\` ADD CONSTRAINT \`FK_565cbf97ee9de5d1f046e01ea8b\` FOREIGN KEY (\`shipping_channel_id\`) REFERENCES \`shippings\`(\`shipping_channel_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        // await queryRunner.query(`ALTER TABLE \`shippings\` CHANGE \`desc\` \`desc\` text NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`images\` CHANGE \`product_id\` \`product_id\` int NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`brands\` CHANGE \`image_url\` \`image_url\` varchar(255) NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`image_url\` \`image_url\` varchar(255) NULL DEFAULT 'NULL'`);
        // await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`parent_cate_id\` \`parent_cate_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`shops\` DROP COLUMN IF EXISTS \`shop_location\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP COLUMN IF EXISTS \`cart_id\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN IF EXISTS \`length\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN IF EXISTS \`height\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN IF EXISTS \`width\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN IF EXISTS \`weight\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN IF EXISTS \`discount\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN IF EXISTS \`price_range_max_old\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN IF EXISTS \`price_range_min_old\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN IF EXISTS \`price_range_max\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN IF EXISTS \`price_range_min\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`range_max_price\` int NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`range_min_price\` int NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`options\` ADD \`product_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`DROP INDEX \`IDX_8d17fb61344ff9acf7b706ae02\` ON \`product_options\``);
        await queryRunner.query(`DROP INDEX \`IDX_49677f87ad61a8b2a31f33c8a2\` ON \`product_options\``);
        await queryRunner.query(`DROP TABLE \`product_options\``);
        await queryRunner.query(`DROP TABLE \`shipping_product_infos\``);
        // await queryRunner.query(`CREATE UNIQUE INDEX \`REL_be02d0f6a15bc7a0d835f832b6\` ON \`attribute_values\` (\`attribute_id\`)`);
        await queryRunner.query(`ALTER TABLE \`addresses\` ADD CONSTRAINT \`FK_9d48998b97e7a97c4fddab1463b\` FOREIGN KEY (\`shop\`) REFERENCES \`shops\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`addresses\` ADD CONSTRAINT \`FK_3e27a8fc336ce24a08833ae34f2\` FOREIGN KEY (\`user\`) REFERENCES \`users\`(\`_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shops\` ADD CONSTRAINT \`FK_bb9c758dcc60137e56f6fee72f7\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD CONSTRAINT \`FK_ad4336ea52ca96a9094a76cd9f3\` FOREIGN KEY (\`shop_id\`) REFERENCES \`shops\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD CONSTRAINT \`FK_30e89257a105eab7648a35c7fce\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carts\` ADD CONSTRAINT \`FK_2ec1c94a977b940d85a4f498aea\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_9e952e93f369f16e27dd786c33f\` FOREIGN KEY (\`shop_id\`) REFERENCES \`shops\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` ADD CONSTRAINT \`FK_84d26b8d3aca1b113b0a423b83c\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` ADD CONSTRAINT \`FK_6343513e20e2deab45edfce1316\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`option_values\` ADD CONSTRAINT \`FK_866eecd9bde39fd5bc4b8d86369\` FOREIGN KEY (\`option_id\`) REFERENCES \`options\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`options\` ADD CONSTRAINT \`FK_8f509b13eba74e88f50da0d1133\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`images\` ADD CONSTRAINT \`FK_96fabbb1202770b8e6a58bf6f1d\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
